title: MY BLOG
author: Connor
email: connor.colson@ibm.com
description: > # this means to ignore newlines until "baseurl:"
  This is a shoddy site that I expect will be destroyed soon.

# social links
twitter_username: cococolson # DO NOT include the @ character, or else the build will fail!
github_username:  cococolsonIBM # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
